name: task_1
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  build: ^2.4.2
  # path: ^1.8.0

dev_dependencies:
  build_config: ^1.1.2
  build_runner: ^2.4.15
  lints: ^5.0.0
  test: ^1.24.0
